### ISSUE TITLE
`pip install jupyterSigplot` doesn't work

### ISSUE THREAD

**Issue by angelobonet** [LGSInnovations/jupyter-sigplot#1]

**Comment by mrecachinas** [comment]
@angelobonet We need to publish jupyter-sigplot to pypi. In the meantime, you should be able to clone this repo and `python setup.py install`.

**Comment by mrecachinas** [comment]
@angelobonet OK - I just published jupyter-sigplot to test.pypi.org, so you should be able to install it with

```
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple jupyter-sigplot
```

Let @maihde or I know if you run into any issues.

**Comment by mrecachinas** [comment]
@angelobonet I verified it worked on my Mac. My environment is below:

```
macOS 10.13.6
Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Python 2.7.15
Jupyter v4.4.0
Jupyter Notebook v5.4.1
```

Because of this, I've pushed version 0.1.0 up to [PyPI](https://pypi.org/project/jupyter-sigplot/). You should now be able to `pip install jupyter-sigplot`. Again, let @maihde or me know if you run into any issues.

Closing this issue.
