### ISSUE TITLE
Make sure local href/file references still work if kernel changes directory

### ISSUE THREAD

**Issue by sterre** [LGSInnovations/jupyter-sigplot#17]
Some of the logic for caching URLs and symlinking files assumes that the kernel's cwd matches that of the jupyter notebook server. I believe some things will break if the kernel issues a `chdir`.

**Comment by mrecachinas** [comment]
@sterre So unfortunately we can't do anything clever like in the `import jupyter_sigplot` set a variable to the cwd because you could easily envision:

```python
import os
os.chdir('..')
import jupyter_sigplot
```

So, I have two thoughts on this:
1. I have never witnessed `os.chdir` first-hand in a Python script, no less in a Jupyter Notebook. I think this is very uncommon, but I agree it needs to be addressed. Perhaps for now we document this case as an antipattern (e.g., "if you do an `os.getcwd()`, you won't be able to plot) for Jupyter-Sigplot until we can devise a more elegant solution?
2. We could do a recursive directory search (à la `find`), and recurse up the tree until we find the notebook's directory, then determine the shortest path from cwd to notebook. (I strongly dislike this idea because it's terribly inefficient.)

What do you think? Also, @maihde any thoughts?

**Comment by maihde** [comment]
I haven’t looked at this in detail, but if you want to find the path
relative to the script (rather than relative to the CWD) I use this pattern:

mydir = os.path.abspath(os.dirname(jupyter_sigplot.__file__))

Michael

**Comment by mrecachinas** [comment]
FWIW, I asked in Jupyter's gitter about this and this was their only proposed solution:
> If you have a kernel extension, you can try to record the cwd as early as possible and use that, rather than resolving cwd at each call
