### ISSUE TITLE
Modify Disabled Keyboard Shortcut to be per focused cell

### ISSUE THREAD

**Issue by mrecachinas** [LGSInnovations/jupyter-sigplot#30]

**Comment by sterre** [comment]
Sure enough, I just spent about 5 seconds wondering why `m` wasn't working in my notebook (I was creating a markdown cell). Per focused cell will be a better scope for this.

**Comment by jrmims** [comment]
I've been digging into this issue and not found a solution yet. It looks like each cell shares a keyboard_manager. If you disable a shortcut from one cell, you disable it from all cells.

**Comment by sterre** [comment]
It's definitely worse to have random keypresses intercepted by SigPlot widgets than to miss some Jupyter keyboard shortcuts. However, I thought I had run into the problem of SigPlot swallowing `m` again recently (last day or two, current with upstream). I'll have to see if I can reproduce that.

My only thought, and @maihde / @mrecachinas probably have already looked at this some, is to get to the bottom of why SigPlot is intercepting those keypress events in the first place. It seems like an event handler that stopped propagation and bubbling should be able to coexist with Jupyter and JSFiddle just fine.

**Comment by mrecachinas** [comment]
That's interesting that you witnessed SigPlot intercepting keypresses -- my experience with Jupyter's keyboard shortcuts is I tried to press 'm' to pull up the menu while the plot was in focus and Jupyter turned my cell into markdown (and therefore totally blowing the plot away). This seems consistent with the behavior others on StackExchange and such have identified.

**Comment by sterre** [comment]
Yeah, I was just running into this again today. I had a couple of plots up in a notebook, and was trying to write explanatory text about them. I would insert a cell, then manually turn it into Markdown, then start typing. The word "example" always stopped typing after the m. I never got a good formula for recovering, but sometimes a bunch of numerals, returns, and escapes did the trick. Similar if I tried to type `import` into a code cell. Sometimes an element would pop up showing me keyboard shortcuts for Jupyter itself too. Additionally, the scroll wheel on my mouse no longer scrolled the document, which was irritating.

I wonder if this behavior tends to be worse with multiple plots in a notebook?

**Comment by sterre** [comment]
I just removed my jupyter-sigplot extension and rebuild from HEAD. I'll see if this behavior crops up again or not--I didn't think to check the hash in my extension before I deleted it.

**Comment by sterre** [comment]
One thing I did not expect, but that I think I'm observing, is that the `m` keyboard shortcut is disabled across all my notebooks from the same server. Does that seem surprising? (In other words, even in notebooks that don't import jupyter-sigplot at all.)

**Comment by sterre** [comment]
Here's something: I just noticed that after `pip uninstall jupyter-sigplot`, I could still import `jupyter_sigplot`. Wat? Turns out I had both a user (`pip install --user`) and a system-level (`pip install`) install, at different versions. I wouldn't be surprised if I was just seeing the old behavior when I accidentally fell back to a system install after deleting my user install.

**Comment by mrecachinas** [comment]
@sterre That's definitely an issue. I would expect it to _only_ be in the notebook that has Jupyter-Sigplot.

Let me know if any recent version fixes it. @jrmims will keep looking on our end.

**Comment by jrmims** [comment]
I just tested with a fresh build. When writing in a new cell, but with my mouse accidentally hovering over a sigplot plot, keys were intercepted. m pulled up a menu, t displayed "time = unk", and r removed the x/y dy/dx cursor values.

With my mouse not hovering over the plot, no keys were intercepted.

I assume in the standard sigplot application, these keys are supposed to do these actions?

**Comment by mrecachinas** [comment]
@jrmims yep that is correct sigplot behavior. If this is the case, then we can safely remove the disabled keyboard shortcut JS code. I think that would resolve this issue. Let me know if you disagree @sterre.

**Comment by sterre** [comment]
I am definitely seeing a problem with latest, and it's definitely tricky to reproduce. Attached is the simplest notebook in which I *have* reproduced my problems.

Basically, what happens is that after some sequence of cell evaluations, cell motion with the keyboard, and mouse movement in and out of the cell containing the SigPlot widget, I get to a point where:
* The mouse wheel no longer scrolls the notebook, regardless of where the mouse pointer is, what the highlighted cell is, or whether the highlighted cell is in edit mode or not
* The `m` key no longer functions in the input area of the cell containing the widget, regardless of mouse pointer position
* The `m` key no longer brings up the middle-mouse menu on the SigPlot instance

Sometimes, clicking in the input area of the cell with the widget restores function, and sometimes, even after that, moving the mouse out of the cell, pressing `m`, and moving the mouse back into the cell breaks things again.

The original context where I saw this problem had both a plot and a raster in different cells, and "felt" a little more likely to trigger the behavior.

Since it's so hard to reproduce, I suspect a race condition somewhere, but of course it could be many other things.

[reproducer.zip](https://github.com/LGSInnovations/jupyter-sigplot/files/2798018/reproducer.zip)

**Comment by sterre** [comment]
On another note, one thing that *is* reproducible for me is that if I have the cursor over the SigPlot widget and type `m`, the middle mouse menu pops up on SigPlot *and* the letter `m` appears in the input area of the cell. This is vexing because it essentially corrupts my input.

**Comment by mrecachinas** [comment]
@sterre Would you agree the ideal behavior is: when a plot is clicked on and in focus, it should intercept 'm' and other keystrokes/mouse wheel, but when another cell, no cell, or the input of a cell (i.e., not the plot) is in focus, all should work as expected in a Jupyter Notebook? Furthermore, when a plot is _hovered over_, it should not intercept any keystrokes?

**Comment by sterre** [comment]
On yet another related note, if I have two SigPlot widgets in the same notebook, I move the mouse over one of them and press `m`, then move the mouse over the *other* one and press `m`, the second SigPlot does not pop up its middle-mouse menu. Furthermore, while that first middle-mouse menu is up, the `m` key is nonfunctional in every other cell I've tried (including Markdown and code cells). The `p` key pressed in another cell's input area brings up the "plugins" menu in the original SigPlot's still-active middle-mouse menu, though. So it appears that SigPlot is eagerly intercepting keypresses from everywhere while its middle-mouse menu is up.

**Comment by sterre** [comment]
> @sterre Would you agree the ideal behavior is: when a plot is clicked on and in focus, it should intercept 'm' and other keystrokes/mouse wheel, but when another cell, no cell, or the input of a cell (i.e., not the plot) is in focus, all should work as expected in a Jupyter Notebook? Furthermore, when a plot is _hovered over_, it should not intercept any keystrokes or mousewheel?

I think yes, with the slight alteration that I also think I should be able to use the keyboard to navigate to the cell containing SigPlot, press Enter to get that cell in edit mode, and *then* move the mouse pointer over the SigPlot widget to interact with it (in other words, not just "clicked on")

**Comment by mrecachinas** [comment]
@maihde We mayneed to modify the way SigPlot adds event handlers to address this.

**Comment by mrecachinas** [comment]
For now, I have reverted 0d674bfb2f4b4781ed4af58d510d5838d60d52f8 (see bf9eab442ca4c7ef767f901bff4d9565ba62df10).

**Comment by mrecachinas** [comment]
@sterre Closing this for now as there is no Jupyter-supported way to disable Jupyter-specific keyboard shortcuts per cell. Let me know what issues you see and we'll attempt to fix them as they come up.
